version: '1'
name: 'professor-of-curvature'
services:
  read-around:
    build: .
    restart: on-failure
    container_name: 'professor-of-curvature'
    read_only: true
    ports:
      - 8302:8010